import 'cuisine_type_description.dart';

enum CuisineType {
  other, // Other at index 0
  american,
  asian,
  beer,
  breakfast,
  burger,
  candy,
  chinese,
  coffee,
  danish,
  dessert,
  doughnuts,
  estonian,
  finnish,
  french,
  german,
  greek,
  healthy,
  hot_dog,
  ice_cream,
  indian,
  israeli,
  italian,
  japanese,
  kebab,
  lebanese,
  mexican,
  nepalese,
  noodles,
  pasta,
  pizza,
  portuguese,
  russian,
  salad,
  sandwiches,
  seafood,
  smoothie,
  soup,
  spanish,
  steak,
  street_food,
  sushi,
  swedish,
  tacos,
  thai,
  turkish,
  united_kingdom,
  vietnamese,
  wine,
  wings
}

final String pathPrefix = 'assets/icons/';

final Map<CuisineType, CuisineTypeDescription> cuisineTypeDescriptions = {
  CuisineType.american: CuisineTypeDescription('American', pathPrefix + 'american.png'),
  CuisineType.asian: CuisineTypeDescription('Asian', pathPrefix + 'asian.png'),
  CuisineType.beer: CuisineTypeDescription('Beer', pathPrefix + 'beer.png'),
  CuisineType.breakfast: CuisineTypeDescription('Breakfast', pathPrefix + 'breakfast.png'),
  CuisineType.burger: CuisineTypeDescription('Burger', pathPrefix + 'burger.png'),
  CuisineType.candy: CuisineTypeDescription('Candy', pathPrefix + 'candy.png'),
  CuisineType.chinese: CuisineTypeDescription('Chinese', pathPrefix + 'chinese.png'),
  CuisineType.coffee: CuisineTypeDescription('Coffee', pathPrefix + 'coffee.png'),
  CuisineType.danish: CuisineTypeDescription('Danish', pathPrefix + 'danish.png'),
  CuisineType.dessert: CuisineTypeDescription('Dessert', pathPrefix + 'dessert.png'),
  CuisineType.doughnuts: CuisineTypeDescription('Doughnuts', pathPrefix + 'doughnuts.png'),
  CuisineType.estonian: CuisineTypeDescription('Estonian', pathPrefix + 'estonian.png'),
  CuisineType.finnish: CuisineTypeDescription('Finnish', pathPrefix + 'finnish.png'),
  CuisineType.french: CuisineTypeDescription('French', pathPrefix + 'french.png'),
  CuisineType.german: CuisineTypeDescription('German', pathPrefix + 'german.png'),
  CuisineType.greek: CuisineTypeDescription('Greek', pathPrefix + 'greek.png'),
  CuisineType.healthy: CuisineTypeDescription('Healthy', pathPrefix + 'healthy.png'),
  CuisineType.hot_dog: CuisineTypeDescription('Hot dog', pathPrefix + 'hot_dog.png'),
  CuisineType.ice_cream: CuisineTypeDescription('Ice cream', pathPrefix + 'ice_cream.png'),
  CuisineType.indian: CuisineTypeDescription('Indian', pathPrefix + 'indian.png'),
  CuisineType.israeli: CuisineTypeDescription('Israeli', pathPrefix + 'israeli.png'),
  CuisineType.italian: CuisineTypeDescription('Italian', pathPrefix + 'italian.png'),
  CuisineType.japanese: CuisineTypeDescription('Japanese', pathPrefix + 'japanese.png'),
  CuisineType.kebab: CuisineTypeDescription('Kebab', pathPrefix + 'kebab.png'),
  CuisineType.lebanese: CuisineTypeDescription('Lebanonese', pathPrefix + 'lebanonese.png'),
  CuisineType.mexican: CuisineTypeDescription('Mexican', pathPrefix + 'mexican.png'),
  CuisineType.nepalese: CuisineTypeDescription('Nepalese', pathPrefix + 'nepalese.png'),
  CuisineType.noodles: CuisineTypeDescription('Noodles', pathPrefix + 'noodles.png'),
  CuisineType.other: CuisineTypeDescription('Other', pathPrefix + 'other.png'),
  CuisineType.pasta: CuisineTypeDescription('Pasta', pathPrefix + 'pasta.png'),
  CuisineType.pizza: CuisineTypeDescription('Pizza', pathPrefix + 'pizza.png'),
  CuisineType.portuguese: CuisineTypeDescription('Portuguese', pathPrefix + 'portuguese.png'),
  CuisineType.russian: CuisineTypeDescription('Russian', pathPrefix + 'russian.png'),
  CuisineType.salad: CuisineTypeDescription('Salad', pathPrefix + 'salad.png'),
  CuisineType.sandwiches: CuisineTypeDescription('Sandwiches', pathPrefix + 'sandwiches.png'),
  CuisineType.seafood: CuisineTypeDescription('Seafood', pathPrefix + 'seafood.png'),
  CuisineType.smoothie: CuisineTypeDescription('Smoothie', pathPrefix + 'smoothie.png'),
  CuisineType.soup: CuisineTypeDescription('Soup', pathPrefix + 'soup.png'),
  CuisineType.spanish: CuisineTypeDescription('Spanish', pathPrefix + 'spanish.png'),
  CuisineType.steak: CuisineTypeDescription('Steak', pathPrefix + 'steak.png'),
  CuisineType.street_food: CuisineTypeDescription('Street food', pathPrefix + 'street_food.png'),
  CuisineType.sushi: CuisineTypeDescription('Sushi', pathPrefix + 'sushi.png'),
  CuisineType.swedish: CuisineTypeDescription('Swedish', pathPrefix + 'swedish.png'),
  CuisineType.tacos: CuisineTypeDescription('Tacos', pathPrefix + 'tacos.png'),
  CuisineType.thai: CuisineTypeDescription('Thai', pathPrefix + 'thai.png'),
  CuisineType.turkish: CuisineTypeDescription('Turkish', pathPrefix + 'turkish.png'),
  CuisineType.united_kingdom: CuisineTypeDescription('United Kingdom', pathPrefix + 'united_kingdom.png'),
  CuisineType.vietnamese: CuisineTypeDescription('Vietnamese', pathPrefix + 'vietnamese.png'),
  CuisineType.wine: CuisineTypeDescription('Wine', pathPrefix + 'wine.png'),
  CuisineType.wings: CuisineTypeDescription('Wings', pathPrefix + 'wings.png'),
};
