name: tablethings
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ^1.20.0

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.3.0
  flutter_bloc: ^6.0.0
  cupertino_icons: ^0.1.2
  http: ^0.12.0
  json_annotation: ^3.0.0

  # Maps
  #google_maps_flutter: any
  #flutter_map: any

  # Widgets
  flutter_rating_bar: ^3.0.0
  flutter_swiper: ^1.1.6
  auto_size_text: ^2.1.0
  flutter_spinkit: ^4.1.1
  credit_card_slider: ^1.0.1

  # QR-scan
  firebase_ml_vision: ^0.9.6
  camera: ^0.5.0

  # Sign in
  google_sign_in: ^4.5.0
  flutter_facebook_login: ^3.0.0

  # Translation
  i18n_extension: ^1.4.0

  # Other
  location: ^2.3.0
  latlong: ^0.6.0
  intl: ^0.16.0
  cached_network_image: ^2.3.0
  uuid: ^2.0.0
  sprintf: ^4.0.0
  permission_handler: ^5.0.0
  jwt_decoder: ^1.0.0
  stripe_payment: ^1.0.0
  credit_card_type_detector: ^1.1.0

dev_dependencies:
  build_runner: ^1.10.0
  json_serializable: ^3.4.0
  flutter_launcher_icons: ^0.7.3
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/tablethings_logo.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # Every subfolder must be added separately
  assets:
    - assets/
    - assets/icons/
    - assets/fonts/

    #- assets/debug/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
        - asset: assets/fonts/nunito/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/nunito/Nunito-ExtraLight.ttf
          weight: 500
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/nunito/Nunito-Black.ttf
          weight: 900
