name: tablething
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^3.2.0
  flutter_bloc: ^2.0.0
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2

  google_maps_flutter: any
  flutter_map: any
  user_location: any
  flutter_map_marker_cluster: any # Not used atm
  flutter_rating_bar: ^3.0.0

  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_ml_vision: ^0.9.3+3

  firebase_auth: ^0.15.0+1
  google_sign_in: ^4.0.14
  flutter_facebook_login: ^3.0.0

  cloud_firestore: ^0.12.11
  firestore_helpers: ^3.2.1+1
  location: ^2.3.5
  latlong: ^0.6.1
  camera: any
  intl: ^0.16.0
  cached_network_image: ^1.1.3
  uuid: ^2.0.4
  json_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # Every subfolder must be added separately
  assets:
    - assets/
    - assets/icons/
    - assets/debug/
    - assets/fonts/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
        - asset: assets/fonts/nunito/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/nunito/Nunito-ExtraLight.ttf
          weight: 500
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/nunito/Nunito-Black.ttf
          weight: 900
