import 'package:tablething/models/cuisine_type_description.dart';
import 'package:tablething/localization/translate.dart';

enum CuisineType {
  american,
  asian,
  beer,
  breakfast,
  burger,
  candy,
  chinese,
  coffee,
  danish,
  dessert,
  doughnuts,
  estonian,
  finnish,
  french,
  german,
  greek,
  healthy,
  hot_dog,
  ice_cream,
  indian,
  israeli,
  italian,
  japanese,
  kebab,
  lebanonese,
  mexican,
  nepalese,
  noodles,
  other,
  pasta,
  pizza,
  portuguese,
  russian,
  salad,
  sandwiches,
  seafood,
  smoothie,
  soup,
  spanish,
  steak,
  street_food,
  sushi,
  swedish,
  tacos,
  thai,
  turkish,
  united_kingdom,
  vietnamese,
  wine,
  wings
}

final String pathPrefix = 'assets/icons/';

final Map<CuisineType, CuisineTypeDescription> cuisineTypeDescriptions = {
  CuisineType.american: CuisineTypeDescription(t('American'), pathPrefix + 'american.png'),
  CuisineType.asian: CuisineTypeDescription(t('Asian'), pathPrefix + 'asian.png'),
  CuisineType.beer: CuisineTypeDescription(t('Beer'), pathPrefix + 'beer.png'),
  CuisineType.breakfast: CuisineTypeDescription(t('Breakfast'), pathPrefix + 'breakfast.png'),
  CuisineType.burger: CuisineTypeDescription(t('Burger'), pathPrefix + 'burger.png'),
  CuisineType.candy: CuisineTypeDescription(t('Candy'), pathPrefix + 'candy.png'),
  CuisineType.chinese: CuisineTypeDescription(t('Chinese'), pathPrefix + 'chinese.png'),
  CuisineType.coffee: CuisineTypeDescription(t('Coffee'), pathPrefix + 'coffee.png'),
  CuisineType.danish: CuisineTypeDescription(t('Danish'), pathPrefix + 'danish.png'),
  CuisineType.dessert: CuisineTypeDescription(t('Dessert'), pathPrefix + 'dessert.png'),
  CuisineType.doughnuts: CuisineTypeDescription(t('Doughnuts'), pathPrefix + 'doughnuts.png'),
  CuisineType.estonian: CuisineTypeDescription(t('Estonian'), pathPrefix + 'estonian.png'),
  CuisineType.finnish: CuisineTypeDescription(t('Finnish'), pathPrefix + 'finnish.png'),
  CuisineType.french: CuisineTypeDescription(t('French'), pathPrefix + 'french.png'),
  CuisineType.german: CuisineTypeDescription(t('German'), pathPrefix + 'german.png'),
  CuisineType.greek: CuisineTypeDescription(t('Greek'), pathPrefix + 'greek.png'),
  CuisineType.healthy: CuisineTypeDescription(t('Healthy'), pathPrefix + 'healthy.png'),
  CuisineType.hot_dog: CuisineTypeDescription(t('Hot dog'), pathPrefix + 'hot_dog.png'),
  CuisineType.ice_cream: CuisineTypeDescription(t('Ice cream'), pathPrefix + 'ice_cream.png'),
  CuisineType.indian: CuisineTypeDescription(t('Indian'), pathPrefix + 'indian.png'),
  CuisineType.israeli: CuisineTypeDescription(t('Israeli'), pathPrefix + 'israeli.png'),
  CuisineType.italian: CuisineTypeDescription(t('Italian'), pathPrefix + 'italian.png'),
  CuisineType.japanese: CuisineTypeDescription(t('Japanese'), pathPrefix + 'japanese.png'),
  CuisineType.kebab: CuisineTypeDescription(t('Kebab'), pathPrefix + 'kebab.png'),
  CuisineType.lebanonese: CuisineTypeDescription(t('Lebanonese'), pathPrefix + 'lebanonese.png'),
  CuisineType.mexican: CuisineTypeDescription(t('Mexican'), pathPrefix + 'mexican.png'),
  CuisineType.nepalese: CuisineTypeDescription(t('Nepalese'), pathPrefix + 'nepalese.png'),
  CuisineType.noodles: CuisineTypeDescription(t('Noodles'), pathPrefix + 'noodles.png'),
  CuisineType.other: CuisineTypeDescription(t('Other'), pathPrefix + 'other.png'),
  CuisineType.pasta: CuisineTypeDescription(t('Pasta'), pathPrefix + 'pasta.png'),
  CuisineType.pizza: CuisineTypeDescription(t('Pizza'), pathPrefix + 'pizza.png'),
  CuisineType.portuguese: CuisineTypeDescription(t('Portuguese'), pathPrefix + 'portuguese.png'),
  CuisineType.russian: CuisineTypeDescription(t('Russian'), pathPrefix + 'russian.png'),
  CuisineType.salad: CuisineTypeDescription(t('Salad'), pathPrefix + 'salad.png'),
  CuisineType.sandwiches: CuisineTypeDescription(t('Sandwiches'), pathPrefix + 'sandwiches.png'),
  CuisineType.seafood: CuisineTypeDescription(t('Seafood'), pathPrefix + 'seafood.png'),
  CuisineType.smoothie: CuisineTypeDescription(t('Smoothie'), pathPrefix + 'smoothie.png'),
  CuisineType.soup: CuisineTypeDescription(t('Soup'), pathPrefix + 'soup.png'),
  CuisineType.spanish: CuisineTypeDescription(t('Spanish'), pathPrefix + 'spanish.png'),
  CuisineType.steak: CuisineTypeDescription(t('Steak'), pathPrefix + 'steak.png'),
  CuisineType.street_food: CuisineTypeDescription(t('Street food'), pathPrefix + 'street_food.png'),
  CuisineType.sushi: CuisineTypeDescription(t('Sushi'), pathPrefix + 'sushi.png'),
  CuisineType.swedish: CuisineTypeDescription(t('Swedish'), pathPrefix + 'swedish.png'),
  CuisineType.tacos: CuisineTypeDescription(t('Tacos'), pathPrefix + 'tacos.png'),
  CuisineType.thai: CuisineTypeDescription(t('Thai'), pathPrefix + 'thai.png'),
  CuisineType.turkish: CuisineTypeDescription(t('Turkish'), pathPrefix + 'turkish.png'),
  CuisineType.united_kingdom: CuisineTypeDescription(t('United Kingdom'), pathPrefix + 'united_kingdom.png'),
  CuisineType.vietnamese: CuisineTypeDescription(t('Vietnamese'), pathPrefix + 'vietnamese.png'),
  CuisineType.wine: CuisineTypeDescription(t('Wine'), pathPrefix + 'wine.png'),
  CuisineType.wings: CuisineTypeDescription(t('Wings'), pathPrefix + 'wings.png'),
};
